apiVersion: v1
kind: Service
metadata:
  name: checkr-bc-database-service
spec:
  selector:
    type: mysql-pod-label
    app: database-pod
  type: NodePort
  ports:
  - targetPort: 3306
    port: 3306