apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc104-user-service-deployment
  labels:
    type: service
    name: user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service-label
    spec:
      containers:
      - name: user-service-container
        image: ghcr.io/pranjal-mukherjee/bootcamp104-backend-user-service:v6
        ports:
        - containerPort: 8083
        env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-registry-svc:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.147.8.88:31025/chekr
            - name: EUREKA_INSTANCE_HOSTNAME
              value: user-service-svc
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                  secretKeyRef:
                      name:  database-secret
                      key:  username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                  secretKeyRef:
                      name:  database-secret
                      key:  password
            - name: SPRING_FLYWAY_ENABLED
              value: "false"
      imagePullSecrets: 
      - name: ghcr-secret
      tolerations:
        - effect: NoSchedule
          key: mysize
          operator: "Equal"
          value: medium
  selector:
    matchLabels:
      app: user-service-label
